spring.application.name: shoppingcart
server.port: 8085
spring.jpa.database: POSTGRESQL
spring.datasource.platform:  org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql: true
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl.auto: true
spring.database.driverClassName: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://localhost:5432/shoppingcart
spring.datasource.username: postgres
spring.datasource.password: 123456

servlet.context-path: /shoppingcart

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

