spring:
  application:
    name: gateway-service
server:
  port: 8080
 
eureka:
 client:
   serviceUrl:
    defaultZone: http://localhost:8083/eureka

   cloud:
     gateway:
       routes:
         - id: employeeModule
           uri: lb://FIRST-SERVICE
           predicates:
             - Path=/employee/**
         - id: consumerModule
           uri: lb://SECOND-SERVICE
           predicates:
             - Path=/consumer/**
         - id: productsModule
           uri: lb://PRODUCT-CATALOG
           predicates:
             - Path=/products/**
         - id: cartModule
           uri: lb://SHOPPINGCART
           predicates:
             - Path=/cart/**