
spring:
  application:
    name: product-catalog
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

      spring:
        database: h2
        console: true
        path: /h2

        datasource:
          platform: h2
          url: jdbc:h2:file:~/products
          username: sa
          password:
          driverClassName: org.h2.Driver
          jpa:
            show-sql= true
          database-platform: org.hibernate.dialect.H2Dialect
          hibernate: ddl-auto=update